# This is a config for E2B sandbox template.
# You can use template ID (qkd0lv5oee4amrlssmh7) or template name (vo-clone-build1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vo-clone-build1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vo-clone-build1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vo-clone-build1')

team_id = "f41cf5bd-62e4-4856-aed7-df519ff20847"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vo-clone-build1"
template_id = "qkd0lv5oee4amrlssmh7"
