# This is a config for E2B sandbox template.
# You can use template ID (pt38suh7w6joepukqeox) or template name (vo-clone-build2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vo-clone-build2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vo-clone-build2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vo-clone-build2')

team_id = "f41cf5bd-62e4-4856-aed7-df519ff20847"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vo-clone-build2"
template_id = "pt38suh7w6joepukqeox"
